### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'image'

### ISSUE THREAD

**Issue by sherlockma11** [jianzongwu/DiffSensei#10]
`Traceback (most recent call last):
  File "/home/good/anaconda3/envs/demo-py2.4/lib/python3.10/site-packages/gradio/queueing.py", line 422, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/good/anaconda3/envs/demo-py2.4/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/good/anaconda3/envs/demo-py2.4/lib/python3.10/site-packages/gradio/blocks.py", line 1480, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/good/anaconda3/envs/demo-py2.4/lib/python3.10/site-packages/gradio/blocks.py", line 1263, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/home/good/anaconda3/envs/demo-py2.4/lib/python3.10/site-packages/gradio_image_prompter/image_prompter.py", line 121, in preprocess
    im = super().preprocess(x.image)
AttributeError: 'dict' object has no attribute 'image'`

The type of x is dict, but the code indicated x is PromptData.
I think it is a issue of gradio's version. Could tell me your version? Thanks!

**Comment by jianzongwu** [comment]
I just install the environment following `README.md`. I use python version 3.11. The gradio and gradio-image-prompter version should be the latest.

**Comment by sherlockma11** [comment]
I don't know why, but I reinstalled the package,and it worked.
gradio                            4.44.1
gradio_client                     1.3.0
gradio_image_prompter             0.1.0
I'll make a note in case someone else has the same problem.
